### PR TITLE
Reload fix

### LINKED ISSUE #328: Expected receiver of type com.facebook.react.ReactActivity, but got
Hi, in my code,my React related Activity,like MyReactActivity did not extend the ReactActivity,but extend my own BaseActivity and implement the interface DefaultHardwareBackBtnHandler.The main code is 
` @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mReactRootView = new ReactRootView(this);
        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModuleName("index.android")
                .addPackage(new MainReactPackage())
                .addPackage(new CodePush(CODE_PUSH_KEY, this, BuildConfig.DEBUG))
                .setJSBundleFile(CodePush.getBundleUrl())
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();
        mReactRootView.startReactApplication(mReactInstanceManager, "testApp", null);

        setContentView(mReactRootView);
    }`
when I use code-push release some update by cli,then I restart the MyReactActivity,I got a crash and the bellow error info
`java.lang.IllegalArgumentException: Expected receiver of type com.facebook.react.ReactActivity, but got com.meicai.mall.activity.MyReactActivity_
                                                  at java.lang.reflect.Field.get(Native Method)
                                                  at com.microsoft.codepush.react.CodePush$CodePushNativeModule.loadBundle(CodePush.java:400)
                                                  at com.microsoft.codepush.react.CodePush$CodePushNativeModule.restartApp(CodePush.java:648)`
then I checked the CodePush.java and located where the error was thrown,the code is 
`Field instanceManagerField = ReactActivity.class.getDeclaredField("mReactInstanceManager");
                instanceManagerField.setAccessible(true); // Make a private field accessible
                final Object instanceManager = instanceManagerField.get(mainActivity);`.
In there, expected mainActivity type is ReactActivity,but in my code，it is not.I also found the above code is wrapped by try-catch,but the expect error type is ReflectiveOperationException,it is not extend the IllegalArgumentException,so the APP crashed at last.By the way,after the crash happened,I reopen the App and found the released update have been deployed my device.

### PR DESCRIPTION
**Pull request by lostintangent**
This fixes #328 by checking the running `Activity` for compatibility before attempting to reflect on it.

### CODE REVIEW

File: android/app/src/main/java/com/microsoft/codepush/react/CodePush.java [hunk 1]
```diff
@@ -403,6 +403,13 @@ private void loadBundleLegacy() {
         private void loadBundle() {
             CodePush.this.clearDebugCacheIfNeeded();
 
+            // Our preferred reload logic relies on the user's Activity inheriting from the
+            // core ReactActivity class, so if doesn't, we just fallback to legacy behavior.
```
Comment (shishirx34) [inline android/app/src/main/java/com/microsoft/codepush/react/CodePush.java]: nit: ...so if __it__ doesn't...

**Comment by shishirx34** [comment]
LGTM
