### PR TITLE
Fix #477 - link errors with multiple AppDelegate.m

### LINKED ISSUE #477: Installation failure at react-native link react-native-code-push
Hey guys,

Trying to implement code push with an existing react native app. We're using react-native-cli: 0.2.0 and react-native: 0.30.0-rc.0. 
During installation `npm install --save react-native-code-push@latest`
I got an UNMET PEER DEPENDENCY react-native@0.30.0-rc.0

I tried to run `react-native link react-native-code-push` after that, which crashed (probably due to the error above). full crash log below.

Is this error related to the react-native version I'm on? Any ideas how to resolve? From the getting started guide I see that RN 0.30 is supported.

```
/Users/shahram/iago/pierogi/node_modules/react-native-code-push/scripts/postlink/ios/postlink.js:26
var oldJsCodeLocationAssignmentStatement = appDelegateContents.match(/(jsCodeLocation = .*)\n/)[1];
                                                                                               ^

TypeError: Cannot read property '1' of null
    at Object.<anonymous> (/Users/shahram/iago/pierogi/node_modules/react-native-code-push/scripts/postlink/ios/postlink.js:26:96)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/shahram/iago/pierogi/node_modules/react-native-code-push/scripts/postlink/run.js:1:63)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
/Users/shahram/iago/pierogi/node_modules/react-native/local-cli/rnpm/core/src/makeCommand.js:21
        throw new Error(`Error occured during executing "${ command }" command`);
        ^

Error: Error occured during executing "node node_modules/react-native-code-push/scripts/postlink/run" command
    at ChildProcess.prelink (/Users/shahram/iago/pierogi/node_modules/react-native/local-cli/rnpm/core/src/makeCommand.js:21:15)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

```

### PR DESCRIPTION
**Pull request by hilkeheremans**
Fixes issue #477 aka `TypeError: Cannot read property '1' of null` when you try to `rnpm link` or `react-native link`.

In issue #477 there was an issue when the project has, for some reason, multiple `AppDelegate.m` files (eg project sample files) within the `ios` subdir of an RN project.

This fix will give priority to the `AppDelegate.m` found inside any path that has the application name (as defined in `package.json`) in it. If it cannot find that, it will revert to previous behavior (the first element in the path array).

### CODE REVIEW

File: scripts/postlink/ios/postlink.js [hunk 1]
```diff
@@ -4,8 +4,20 @@ var inquirer = require('inquirer');
 var path = require("path");
 var plist = require("plist");
 
+// Fix for https://github.com/Microsoft/react-native-code-push/issues/477
+// Try to resolve package.json, assuming we are working off of the project root
+// We will use this later to fetch the correct AppDelegate and Plist file, in case there are multiple.
+var package = require(path.resolve('./package.json'));
```
Comment (silhouettes) [inline scripts/postlink/ios/postlink.js]: Correct me if I'm wrong, but I think the end result would be the same if this was just `require("./package.json");` (note the double quotes also).

Also, I don't think you need the comment above - the comment below does a great job explaining everything.

File: scripts/postlink/ios/postlink.js [hunk 2]
```diff
@@ -4,8 +4,20 @@ var inquirer = require('inquirer');
...
+
 var ignoreNodeModules = { ignore: "node_modules/**" };
-var appDelegatePath = glob.sync("**/AppDelegate.m", ignoreNodeModules)[0];
+var appDelegatePaths = glob.sync("**/AppDelegate.m", ignoreNodeModules);
+
+// Fix for https://github.com/Microsoft/react-native-code-push/issues/477:
+// Typical location of AppDelegate.m for newer RN versions: $PROJECT_ROOT/ios/<project_name>/AppDelegate.m
+// Try to find that path by filtering the whole array for any path containing <project_name>
+// If we can't find it there, play dumb and pray it is the first path we find.
+var appDelegatePath = findFileByAppName(appDelegatePaths, package?package.name:null) || appDelegatePaths[0];
```
Comment (silhouettes) [inline scripts/postlink/ios/postlink.js]: Small nit - we generally put spaces between ternary operators (i.e. `package ? package.name : null`)

Comment (hilkeheremans) [inline scripts/postlink/ios/postlink.js]: Will do, I will correct tomorrow. Thanks for your feedback!

**Comment by silhouettes** [comment]
Thanks for this @hilkeheremans, this is a very clever fix! I just have some small style comments I left - if you could address those, I would love to merge this!

File: scripts/postlink/ios/postlink.js (hunk 1 above)
Comment (silhouettes) [inline scripts/postlink/ios/postlink.js]: Ohh, that sounds plausible. I guess maybe `require("./package.json")` resolves relative to `__dirname` (the folder the file is located in), and `path.resolve("./package.json")` resolves relative to the user's pwd.  This makes sense to me!

Comment (hilkeheremans) [inline scripts/postlink/ios/postlink.js]: Right on the mark @silhouettes: it just requires off of `__dirname`. I must have forgotten a `../` somewhere (a mistake easily made when the file is that deep).

Let's keep things idiomatic and just use a normal `require`. PR update coming in.

**Comment by hilkeheremans** [comment]
There, fixed that stuff per your request. Good luck! ;-)

**Comment by silhouettes** [comment]
Great stuff :)

**Comment by Choicelin** [comment]
the issue still happen after this merge

**Comment by hilkeheremans** [comment]
Could you specify a little more? Works fine here, so perhaps it is something different yet closely related.
