### PR TITLE
Guard against NSError null pointer dereferences

### LINKED ISSUE #490: [iOS] Methods that take NSError references should guard against null pointer dereference
- Methods in the iOS SDK do not currently guard against null pointer dereferences, they should.
- Example:

```Objective-C
+ (NSMutableDictionary *)getCurrentPackageInfo:(NSError **)error
{
    NSString *statusFilePath = [self getStatusFilePath];
    if (![[NSFileManager defaultManager] fileExistsAtPath:statusFilePath]) {
        return [NSMutableDictionary dictionary];
    }
    
    NSString *content = [NSString stringWithContentsOfFile:statusFilePath
                                                  encoding:NSUTF8StringEncoding
                                                     error:error];
    if (*error) {
        return nil;
    }
    
    NSData *data = [content dataUsingEncoding:NSUTF8StringEncoding];
    NSDictionary* json = [NSJSONSerialization JSONObjectWithData:data
                                                         options:kNilOptions
                                                           error:error];
    if (*error) {
        return nil;
    }
    
    return [json mutableCopy];
}
```

- This method crashes if called like this: `[CodePush getCurrentPackageInfo:nil];`
- This method should use a `localError` object for the internal method calls that pass back an `NSError` instance, then check `if (error)` rather than `if (*error)`

### PR DESCRIPTION
**Pull request by daniel-beard**
- This fixes #490 
- Guards against null dereference of `NSError **` pointers.
- Fixes some of the fragile error checks.
- Future fixes here may require changing some public method signatures, as all methods that take an `NSError **` parameter should at *least* return a `BOOL` indicating success/failure. I haven't done that in this PR, as I wasn't sure how this team handles breaking API changes.
- Conform to best practices outlined here: https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/ErrorHandling/ErrorHandling.html

### CODE REVIEW

File: ios/CodePush/CodePushPackage.m [hunk 1]
```diff
@@ -292,26 +292,41 @@ + (NSString *)getCodePushPath
...
+        if (localError && error) {
+            *error = localError;
+        }
         return nil;
     }
-    
-    return [CodePushPackage getPackage:packageHash error:error];
+
+    NSDictionary *package = [CodePushPackage getPackage:packageHash error:&localError];
+    if (!package && localError && error) {
```
Comment (geof90) [inline ios/CodePush/CodePushPackage.m]: This seems a little unnecessary (at least to me). Why not just `return [CodePushPackage getPackage:packageHash error:error];`? If `[CodePushPackage getPackage]` deals with the null pointer deference problem too, then that line already achieves all of your goals - 1. To return the result anyway, 2. To only set the `error` pointer pointer if its not nil.

Comment (daniel-beard) [inline ios/CodePush/CodePushPackage.m]: Good point, I'll update this.

**Comment by daniel-beard** [comment]
Not sure how I can sign the CLA, can someone point me in the right direction?

File: ios/CodePush/CodePushPackage.m [hunk 2]
```diff
@@ -391,16 +418,26 @@ + (NSDictionary *)getPackage:(NSString *)packageHash
...
     }
     
     NSData *updateMetadata = [updateMetadataString dataUsingEncoding:NSUTF8StringEncoding];
-    return [NSJSONSerialization JSONObjectWithData:updateMetadata
+    id result = [NSJSONSerialization JSONObjectWithData:updateMetadata
                                            options:kNilOptions
-                                             error:error];
+                                             error:&localError];
+
+    if (!result) {
```
Comment (geof90) [inline ios/CodePush/CodePushPackage.m]: Same comment here.. NSJSONSerialization accepts a nullable error parameter.

File: ios/CodePush/CodePushPackage.m [hunk 3]
```diff
@@ -410,18 +447,33 @@ + (NSString *)getPackageFolderPath:(NSString *)packageHash
...
+        if (localError && error) {
+            *error = localError;
+        }
         return nil;
     }
     
-    return [CodePushPackage getPackage:packageHash error:error];
+    NSDictionary *package = [CodePushPackage getPackage:packageHash error:&localError];
+
+    if (!package) {
```
Comment (geof90) [inline ios/CodePush/CodePushPackage.m]: Same here.

File: ios/CodePush/CodePushPackage.m (hunk 2 above)
Comment (daniel-beard) [inline ios/CodePush/CodePushPackage.m]: If this fails, wouldn't you want the caller of this method to know that it was a failure within `NSJSONSerialization` ?

File: ios/CodePush/CodePushPackage.m (hunk 3 above)
Comment (daniel-beard) [inline ios/CodePush/CodePushPackage.m]: Will Update

File: ios/CodePush/CodePushPackage.m [hunk 4]
```diff
@@ -481,28 +537,33 @@ + (void)installPackage:(NSDictionary *)updatePackage
...
     
     [info setValue:packageHash forKey:@"currentPackage"];
-    
+
+    //TODO: This method should return a BOOL indication of success.
     [self updateCurrentPackageInfo:info
-                             error:error];
+                             error:&localError];
+
+    if (localError && error) {
```
Comment (geof90) [inline ios/CodePush/CodePushPackage.m]: Here too

File: ios/CodePush/CodePushPackage.m [hunk 5]
```diff
@@ -481,28 +537,33 @@ + (void)installPackage:(NSDictionary *)updatePackage
...
+    if (!currentPackageFolderPath) {
         return;
     }
     
     NSError *deleteError;
-    [[NSFileManager defaultManager] removeItemAtPath:currentPackageFolderPath
+    BOOL result = [[NSFileManager defaultManager] removeItemAtPath:currentPackageFolderPath
                                                error:&deleteError];
-    if (deleteError) {
+    if (!result) {
```
Comment (geof90) [inline ios/CodePush/CodePushPackage.m]: This probably isn't part of your change scope, but I think we should print the error too.

**Comment by geof90** [comment]
@daniel-beard You can sign the CLA here: https://cla.microsoft.com/

File: ios/CodePush/CodePushPackage.m (hunk 2 above)
Comment (geof90) [inline ios/CodePush/CodePushPackage.m]: Yes, but that would be achieved by passing the `error` pointer that the caller gave to us directly no?

Comment (daniel-beard) [inline ios/CodePush/CodePushPackage.m]: That's happening below:

```
if (!result) {
  if (localError && error) {   // Makes sure we are dereferencing a null pointer
    *error = localError;         // Assigns the value to the `error` parameter that is passed into the method
  }
}
```

File: ios/CodePush/CodePushUpdateUtils.m [hunk 6]
```diff
@@ -238,18 +273,23 @@ + (BOOL)verifyHashForDiffUpdate:(NSString *)finalUpdateFolder
...
 {
+    NSError *localError;
     NSMutableArray *updateContentsManifest = [NSMutableArray array];
     [self addContentsOfFolderToManifest:finalUpdateFolder
                              pathPrefix:@""
                                manifest:updateContentsManifest
-                                  error:error];
-    if (*error) {
+                                  error:&localError];
+    if (localError && error) {
```
Comment (geof90) [inline ios/CodePush/CodePushUpdateUtils.m]: I think we should return `NO` if the `localError` is set, regardless of whether the `error` is nil?

If you don't like that, feel free to modify the methods in this file to return boolean flags indicating success, since this file doesn't contain public documented APIs.

Comment (daniel-beard) [inline ios/CodePush/CodePushUpdateUtils.m]: Yeah I think that would be best, I'll update.

File: ios/CodePush/CodePushPackage.m (hunk 2 above)
Comment (geof90) [inline ios/CodePush/CodePushPackage.m]: Right.. what I meant was `NSJSONSerialization` takes care of not dereferencing null pointers for you since the documentation says the error param can be nullable. Ultimately, what I'm suggesting is just for brevity, since your code does achieve the same thing

**Comment by geof90** [comment]
@daniel-beard Sorry do you mind resolving the conflicts? I want to get this merged. Thanks!

**Comment by daniel-beard** [comment]
For sure, updating now.

**Comment by daniel-beard** [comment]
Ok @geof90 updated and squashed.

File: ios/CodePush/CodePushPackage.m [hunk 7]
```diff
@@ -292,26 +292,37 @@ + (NSString *)getCodePushPath
...
+    if (!packageHash) {
+        if (localError && error) {
+            *error = localError;
+        }
         return nil;
     }
-    
-    return [CodePushPackage getPackage:packageHash error:error];
+
+    return [CodePushPackage getPackage:packageHash error:&localError];
```
Comment (geof90) [inline ios/CodePush/CodePushPackage.m]: Shouldn't this be `error:error`?

File: ios/CodePush/CodePushUpdateUtils.m [hunk 8]
```diff
@@ -196,19 +229,22 @@ + (NSString *)getHashForBinaryContents:(NSURL *)binaryBundleUrl
...
+            }
             return nil;
         }
     }
     
     [self addFileToManifest:binaryBundleUrl manifest:manifest];
     [self addFileToManifest:[binaryBundleUrl URLByAppendingPathExtension:@"meta"] manifest:manifest];
 
-    binaryHash = [self computeFinalHashFromManifest:manifest error:error];
+    binaryHash = [self computeFinalHashFromManifest:manifest error:&localError];
```
Comment (geof90) [inline ios/CodePush/CodePushUpdateUtils.m]: `error` instead of `&localError`?

Comment (daniel-beard) [inline ios/CodePush/CodePushUpdateUtils.m]: Fixed

File: ios/CodePush/CodePushPackage.m (hunk 7 above)
Comment (daniel-beard) [inline ios/CodePush/CodePushPackage.m]: Fixed

**Comment by geof90** [comment]
I'm sorry for dragging out this PR longer than it needs to, but thinking about this more, I still have a question over why this is the right practice:

1. I see that the motivation for this fix is that we should guard against nil dereferencing `NSError **` pointers, e.g. doing things like `if (*error) { return nil }`.

2. However, you brought out a second problem, which is that checking the error object in the first place is "fragile". I think I am convinced about that.

3. As a result, I'd argue that the fix for 2 would also fix 1 (because we no longer need nor should check returned error pointers, and therefore, dereference them). So why are all the local `*localError` variables needed then?

I'll leave some inline comments to better illustrate what I mean.

File: ios/CodePush/CodePushPackage.m [hunk 9]
```diff
@@ -292,26 +292,37 @@ + (NSString *)getCodePushPath
 
 + (NSDictionary *)getCurrentPackage:(NSError **)error
 {
-    NSString *packageHash = [CodePushPackage getCurrentPackageHash:error];
-    if (*error || !packageHash) {
+    NSError *localError;
+    NSString *packageHash = [CodePushPackage getCurrentPackageHash:&localError];
```
Comment (geof90) [inline ios/CodePush/CodePushPackage.m]: What would be the drawback if we simply passed `error` instead of `&localError` here, if we know that `getCurrentPackageHash` already guards against nil dereferencing `error`?

File: ios/CodePush/CodePushPackage.m [hunk 10]
```diff
@@ -292,26 +292,37 @@ + (NSString *)getCodePushPath
...
+    if (!packageHash) {
+        if (localError && error) {
+            *error = localError;
+        }
```
Comment (geof90) [inline ios/CodePush/CodePushPackage.m]: I think if we passed `error` directly instead of `&localError`, we could simply have

```
if (!packageHash) {
    return nil;
}
```

and get rid of these lines:
```
if (localError && error) {
    *error = localError;
}
```

File: ios/CodePush/CodePushPackage.m [hunk 11]
```diff
@@ -292,26 +292,37 @@ + (NSString *)getCodePushPath
...
     }
-    
+
     return [CodePushPackage getPackage:packageHash error:error];
 }
 
 + (NSString *)getCurrentPackageBundlePath:(NSError **)error
 {
-    NSString *packageFolder = [self getCurrentPackageFolderPath:error];
+    NSError *localError;
```
Comment (geof90) [inline ios/CodePush/CodePushPackage.m]: If possible, I would like to get rid of the need to create this new `localError` entirely, here and the rest of your changes, unless they serve some other purpose which I am missing.

**Comment by geof90** [comment]
Hi @daniel-beard, I want to respect your time, so if you want me to just merge this and I can continue where you left off later, feel free to let me know!

**Comment by daniel-beard** [comment]
I can address the rest of the changes tomorrow :D

**Comment by daniel-beard** [comment]
Ok @geof90 I scrubbed through and removed all the `localError` vars, and made sure there aren't any more fragile error checks. This should be good to go now.

**Comment by geof90** [comment]
Yes! this looks a lot cleaner (and shorter). I will merge this, test and get it published ASAP.
