### PR TITLE
Fix NPE when invoking `copyNecessaryFilesFromCurrentPackage()` method on Android

### LINKED ISSUE #2087: An error occurred while executing doInBackground(), Caused by java.lang.NullPointerException com.microsoft.codepush.react.FileUtils.copyDirectoryContents
### Steps to Reproduce
I wasn't able to reproduce it myself due to lack of this kind of device, but according to the Crashlytics & Sentry stack trace its only happening on `Huawei P30 lite` right after the code push update check (with no new pending updates)

### Expected Behavior
Just normal update check and continue app loading, with the result of no new update

### Actual Behavior
App crashed with the following - 
```
Fatal Exception: java.lang.RuntimeException
An error occurred while executing doInBackground()
    android.os.AsyncTask$4.done (AsyncTask.java:399)
    java.lang.Thread.run (Thread.java:929)
```
```
java.io.File.<init> (File.java:283)
com.microsoft.codepush.react.FileUtils.copyDirectoryContents (FileUtils.java:19)
com.microsoft.codepush.react.CodePushUpdateUtils.copyNecessaryFilesFromCurrentPackage (CodePushUpdateUtils.java:100)
com.microsoft.codepush.react.CodePushUpdateManager.downloadPackage (CodePushUpdateManager.java:242)
com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground (CodePushNativeModule.java:290)
com.microsoft.codepush.react.CodePushNativeModule$3.doInBackground (CodePushNativeModule.java:284)
android.os.AsyncTask$3.call (AsyncTask.java:378)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:929)
```

### Reproducible Demo

I don't have a reproducible Demo, but the way I use code push - 
```js
CodePush({
  checkFrequency: CodePush.CheckFrequency.ON_APP_RESUME,
  installMode: CodePush.InstallMode.ON_NEXT_RESUME,
})
```

### Environment

* react-native-code-push version: **7.0.1**
* react-native version: **0.64.0**
* iOS/Android/Windows version: **Android 10** 
* Does this reproduce on a debug build or release build? **release**
* Does this reproduce on a simulator, or only on a physical device? **physical device - Huawei P30 lite**

Sorry for the lack of reproducible demo and more specific steps, this only started when we rolled out to production

### PR DESCRIPTION
**Pull request by robxyy**
Fix #2087. It looks like NPE is caused by [CodePushUpdateManager.java#L79](https://github.com/microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePushUpdateManager.java#L79). When invoking `copyNecessaryFilesFromCurrentPackage()` method, If `currentPackageFolderPath` is `null`, copying `currentPackageFolderPath` to `newUpdateFolderPath` will be discarded.

### CODE REVIEW

**Comment by DmitriyKirakosyan** [comment]
Hi @robxyy , thank you for the contribution! Let me leave a couple of comments on your change.

File: android/app/src/main/java/com/microsoft/codepush/react/CodePushUpdateUtils.java [hunk 1]
```diff
@@ -97,7 +97,9 @@ private static String computeHash(InputStream dataStream) {
     }
 
     public static void copyNecessaryFilesFromCurrentPackage(String diffManifestFilePath, String currentPackageFolderPath, String newPackageFolderPath) throws IOException {
-        FileUtils.copyDirectoryContents(currentPackageFolderPath, newPackageFolderPath);
+        if (currentPackageFolderPath != null) {
+            FileUtils.copyDirectoryContents(currentPackageFolderPath, newPackageFolderPath);
+        }
         JSONObject diffManifest = CodePushUtils.getJsonObjectFromFile(diffManifestFilePath);
```
Comment (DmitriyKirakosyan) [inline android/app/src/main/java/com/microsoft/codepush/react/CodePushUpdateUtils.java:103]: The rest of the method doesn't seem making sense if `currentPackageFolderPath` is `null`. The logic below will try removing files which don't exist :)

File: android/app/src/main/java/com/microsoft/codepush/react/CodePushUpdateUtils.java [hunk 2]
```diff
@@ -97,7 +97,9 @@ private static String computeHash(InputStream dataStream) {
     }
 
     public static void copyNecessaryFilesFromCurrentPackage(String diffManifestFilePath, String currentPackageFolderPath, String newPackageFolderPath) throws IOException {
-        FileUtils.copyDirectoryContents(currentPackageFolderPath, newPackageFolderPath);
+        if (currentPackageFolderPath != null) {
+            FileUtils.copyDirectoryContents(currentPackageFolderPath, newPackageFolderPath);
+        }
```
Comment (DmitriyKirakosyan) [inline android/app/src/main/java/com/microsoft/codepush/react/CodePushUpdateUtils.java:102]: Also, would be great having some logging here if the path is invalid.

File: android/app/src/main/java/com/microsoft/codepush/react/CodePushUpdateUtils.java [hunk 3]
```diff
@@ -97,7 +97,9 @@ private static String computeHash(InputStream dataStream) {
     }
 
     public static void copyNecessaryFilesFromCurrentPackage(String diffManifestFilePath, String currentPackageFolderPath, String newPackageFolderPath) throws IOException {
-        FileUtils.copyDirectoryContents(currentPackageFolderPath, newPackageFolderPath);
+        if (currentPackageFolderPath != null) {
```
Comment (DmitriyKirakosyan) [inline android/app/src/main/java/com/microsoft/codepush/react/CodePushUpdateUtils.java:100]: In a condition like this I would also expect checking if the path exists on disk.

**Review by DmitriyKirakosyan — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/com/microsoft/codepush/react/CodePushUpdateUtils.java (hunk 1 above)
Comment (robxyy) [reply android/app/src/main/java/com/microsoft/codepush/react/CodePushUpdateUtils.java:103]: From the stack trace, it seems that `diffManifestFilePath` exists, refer [CodePushUpdateManager.java#L239](https://github.com/microsoft/react-native-code-push/blob/master/android/app/src/main/java/com/microsoft/codepush/react/CodePushUpdateManager.java#L239), so I kept the following business logic.

Comment (DmitriyKirakosyan) [reply android/app/src/main/java/com/microsoft/codepush/react/CodePushUpdateUtils.java:105]: It might exist, but it would be useful, because if nothing is copied to the destination folder, then there would be nothing to remove.

**Review by MikhailSuendukov — APPROVED** [review]

**Review by DmitriyKirakosyan — APPROVED** [review]

**Review by DergachevE — APPROVED** [review]

**Comment by DordeDimitrijev** [comment]
Hi @robxyy these changes were reverted from release 8.3.0 of rn-codepush and latest 8.3.1 hotfix doesn't include  them. Reason behind this is that customers reported rollbacks of update and I traced it back to these changes. If you wish to keep these changes and resolve this issue take a look https://github.com/microsoft/react-native-code-push/issues/2725

**Comment by robxyy** [comment]
> Hi @robxyy these changes were reverted from release 8.3.0 of rn-codepush and latest 8.3.1 hotfix doesn't include them. Reason behind this is that customers reported rollbacks of update and I traced it back to these changes. If you wish to keep these changes and resolve this issue take a look #2725

Sorry to hear that. I missed `FileUtils.copyDirectoryContents(currentPackageFolderPath, newPackageFolderPath);`, and I will push a PR later.
